env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
  matrix:
      # Stage 1 (as root)
    - TAGS="-t upgrade"
    - TAGS="-t packages_cui_minimal"
    - TAGS="-t os_locale"
    - TAGS="-t os_hostname"      # Breaks on travis
    - TAGS="-t os_pacman"
    - TAGS="-t os_service_networkmanager"
    - TAGS="-t os_service_dnsmasq"
    - TAGS="-t os_service_ntp"
    - TAGS="-t os_service_ufw"
    - TAGS="-t os_service_ssh"
    - TAGS="-t os_service_docker"
    - TAGS="-t os_service_kvm"
      # Stage 2 (as user)
    - TAGS='-t os_gpg_recv_key'                 ENVARS="-e user=travis"
    - TAGS="-t packages_cui_workstation"        ENVARS="-e user=travis"
    - TAGS="-t packages_gui_xorg"               ENVARS="-e user=travis"
    - TAGS="-t packages_gui_awesome_wm"         ENVARS="-e user=travis"
    - TAGS="-t packages_gui_fonts"              ENVARS="-e user=travis"
    - TAGS="-t packages_gui_apps"               ENVARS="-e user=travis"
      # Stage 3 (as user)
    - TAGS='-t os_secrets_pre'                  ENVARS="-e user=travis"
    #- TAGS='-t os_secrets_pos'                  ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_home'                   ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_bb'                     ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_tmux'                   ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_vim'                    ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_zsh'                    ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_apps'                   ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_awesome4'               ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_task'                   ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_fortune_bible'          ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_mutt'                   ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t dotfiles_secrets'                ENVARS="-e user=travis"
    - TAGS='-t packages_cui_minimal -t os_secrets_pre -t user_home_apps'                  ENVARS="-e user=travis"

    - TAGS="-t packages_suite_latex"
    - TAGS="-t packages_suite_libreoffice"
      # AUR
      #    - TAGS="-t yaourt"
      #    - TAGS="-t packages_cui_aur"                ENVARS="-e user=travis"
      #      #- TAGS="-t packages_gui_aur"                ENVARS="-e user=travis"  # >90min
      #      # Devel                                                         "
      #    - TAGS="-t devel_env_python"                ENVARS="-e user=travis"
      #    - TAGS="-t devel_env_ruby"                  ENVARS="-e user=travis"
      #    - TAGS="-t devel_env_node"                  ENVARS="-e user=travis"
      #    #- TAGS="-t devel_env_java"                  ENVARS='-e user=travis'
      #    - TAGS="-t devel_env_r"                     ENVARS="-e user=travis"
      #    - TAGS="-t devel_env_haskell"               ENVARS="-e user=travis"
      #      # Dotfiles                                                      "
      #      # Asdf
      #    #- TAGS="-t dotfiles_home_apps"              ENVARS="-e user=travis"  # >90min
      #    #- TAGS="-t dotfiles_asdf"                   ENVARS="-e user=travis"
      #      # All
      #    #- TAGS="-t all"                             ENVARS="-e user=travis"

language: python
sudo: required

arch:
  packages:
    - yaourt
  script:
    - home/.ansible-dotfiles/scripts/archlinux/setup-archlinux-dependencies.sh
    - sudo home/.ansible-dotfiles/setup-root.sh
    - sudo ansible-playbook home/.ansible-dotfiles/playbook.yml -i local, -c local --sudo $TAGS $ENVARS
      #- sudo home/.ansible-dotfiles/setup-user.sh $TAGS $ENVARS -e is_travis=true -e travis_env=true
      #- ./scripts/test-$TAGS.sh

script:
  - wget https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh
  - chmod 755 arch-travis.sh
  - travis_wait 120 ./arch-travis.sh
