env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
  matrix:
      # Upgrade
    - SCRIPT="playbook-stage1.yml"     TAGS="-t upgrade"
      # Packages
    - TAGS="-t packages_cui_minimal"
    - TAGS="-t packages_cui_workstation"
    - TAGS="-t packages_gui_xorg"
    - TAGS="-t packages_gui_awesome_wm"
    - TAGS="-t packages_gui_fonts"
    - TAGS="-t packages_gui_apps"
      # Writing suite
    - TAGS="-t packages_suite_latex"
    - TAGS="-t packages_suite_libreoffice"
      # OS
    - TAGS="-t os_locale"
    - TAGS="-t os_hostname"      # Breaks on travis
    - TAGS="-t os_pacman"
    - TAGS="-t os_service_networkmanager"
    - TAGS="-t os_service_dnsmasq"
    - TAGS="-t os_service_ntp"
    - TAGS="-t os_service_ufw"
    - TAGS="-t os_service_ssh"
    - TAGS="-t os_service_docker"
    - TAGS="-t os_service_kvm"
      # AUR
    - TAGS="-t yaourt"
    - TAGS="-t packages_cui_aur"                ENVARS="-e user=travis"
      #- TAGS="-t packages_gui_aur"                ENVARS="-e user=travis"  # >90min
      # Devel                                                         "
    - TAGS="-t devel_env_python"                ENVARS="-e user=travis"
    - TAGS="-t devel_env_ruby"                  ENVARS="-e user=travis"
    - TAGS="-t devel_env_node"                  ENVARS="-e user=travis"
    #- TAGS="-t devel_env_java"                  ENVARS='-e user=travis'
    - TAGS="-t devel_env_r"                     ENVARS="-e user=travis"
    - TAGS="-t devel_env_haskell"               ENVARS="-e user=travis"
      # Dotfiles                                                      "
    - TAGS="-t dotfiles_home"                   ENVARS="-e user=travis"
    - TAGS="-t dotfiles_apps"                   ENVARS="-e user=travis"
    - TAGS="-t dotfiles_tmux"                   ENVARS="-e user=travis"
    - TAGS="-t dotfiles_vim"                    ENVARS="-e user=travis"
    - TAGS="-t dotfiles_zsh"                    ENVARS="-e user=travis"
    - TAGS="-t dotfiles_awesome"                ENVARS="-e user=travis"
    - TAGS="-t dotfiles_task"                   ENVARS="-e user=travis"
    - TAGS="-t dotfiles_fortune_bible"          ENVARS="-e user=travis"
      # Asdf
    #- TAGS="-t dotfiles_home_apps"              ENVARS="-e user=travis"  # >90min
    #- TAGS="-t dotfiles_asdf"                   ENVARS="-e user=travis"
      # All
    #- TAGS="-t all"                             ENVARS="-e user=travis"

language: python
sudo: required

arch:
  packages:
    - yaourt
  script:
    - home/.ansible-dotfiles/scripts/archlinux/setup-archlinux-dependencies.sh
    - sudo home/.ansible-dotfiles/setup-root.sh
    - sudo ansible-playbook $SCRIPT -i local, -c local --sudo $TAGS $ENVARS -e is_travis=true -e travis_env=true
      #- sudo home/.ansible-dotfiles/setup-user.sh $TAGS $ENVARS -e is_travis=true -e travis_env=true
      #- ./scripts/test-$TAGS.sh

script:
  - wget https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh
  - chmod 755 arch-travis.sh
  - travis_wait 120 ./arch-travis.sh
