sudo: required

env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
  matrix:
    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg,packages_gui_awesome_wm,packages_gui_fonts,packages_gui_apps,packages_gui_aur"
#    - TAGS="packages_cui_minimal"
#    - TAGS="packages_cui_minimal,packages_cui_workstation"
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur"
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg"
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg,packages_gui_awesome_wm"
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg,packages_gui_awesome_wm,packages_gui_fonts"
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg,packages_gui_awesome_wm,packages_gui_fonts,packages_gui_apps"

#language: c
#
#compiler:
#  - gcc
#  - clang

arch:
#  repos:
#    - archlinuxfr=http://repo.archlinux.fr/$arch
#  packages:
#    - procps-ng
#    - reflector
#    # aur
#    - screenfetch-git
  script:
    - ./bootstrap/archlinux/guest-archlinux-setup-dependencies.sh
    - sudo ansible-playbook -i local, -c local -t $TAGS playbook.yml --sudo

#    - "sudo screenfetch"
#    - "reflector --verbose -l 20 --sort rate -p https"
#    - "echo $CC"
#    - "touch test_file"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
#  - "bash ./arch-travis.sh"
#  - "ls -l"
#  - sudo pacman -Syyu --noconfirm
#  - sudo pacman -S --noconfirm python2-pip
#  - sudo pacman -S --noconfirm ansible
#  - sudo ln -sf /usr/bin/python2 /usr/bin/python
