env:
  global:
    - ARCH_TRAVIS_CLEAN_CHROOT=1
  matrix:
      # Upgrade
    - TAGS="-t upgrade"
      # Packages
    - TAGS="-t packages_cui_minimal"
    - TAGS="-t packages_cui_workstation"
    - TAGS="-t packages_gui_xorg"
    - TAGS="-t packages_gui_awesome_wm"
    - TAGS="-t packages_gui_fonts"
    - TAGS="-t packages_gui_apps"
      # Writing suite
    - TAGS="-t packages_suite_latex"
    - TAGS="-t packages_suite_libreoffice"
      # AUR
    - TAGS="-t yaourt"
    - TAGS="-t packages_cui_aur"                ENVARS='-e user=travis'
    - TAGS="-t packages_gui_aur"                ENVARS='-e user=travis'
      # Devel
    - TAGS="-t devel_env_python"                ENVARS='-e user=travis'
      # All
    - TAGS="-t all"                             ENVARS='-e user=travis'
#    - TAGS="packages_cui_minimal,packages_cui_workstation,packages_cui_aur,packages_gui_xorg,packages_gui_awesome_wm,packages_gui_fonts,packages_gui_apps,packages_gui_aur"

language: python
sudo: required

arch:
  packages:
    - yaourt
  script:
    - ./bootstrap/archlinux/guest-archlinux-setup-dependencies.sh
    - sudo ./setup-root.sh
    - sudo ./setup-user.sh $TAGS $ENVARS -vvvv

script:
  - travis_wait 60 "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
