sudo: required

env:
  - ARCH_TRAVIS_CLEAN_CHROOT=1

#language: c
#
#compiler:
#  - gcc
#  - clang

arch:
#  repos:
#    - archlinuxfr=http://repo.archlinux.fr/$arch
#  packages:
#    - procps-ng
#    - reflector
#    # aur
#    - screenfetch-git
  script:
    - ./bootstrap/archlinux/guest-archlinux-setup-dependencies.sh
    - ansible-playbook -i local, -c local playbook.yml --sudo

#    - "sudo screenfetch"
#    - "reflector --verbose -l 20 --sort rate -p https"
#    - "echo $CC"
#    - "touch test_file"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
#  - "bash ./arch-travis.sh"
#  - "ls -l"
#  - sudo pacman -Syyu --noconfirm
#  - sudo pacman -S --noconfirm python2-pip
#  - sudo pacman -S --noconfirm ansible
#  - sudo ln -sf /usr/bin/python2 /usr/bin/python
