#!/usr/bin/env ansible-playbook --inventory-file=inventory

---
- hosts: all

  roles:
    - { role: upgrade.system, tags: [ 'upgrade' ] }
    - { role: install.list.system.packages, packages_list: "{{ cui_minimal_packages }}", tags: [ 'packages_cui_minimal' ] }
    - { role: install.list.system.packages, packages_list: "{{ cui_workstation_packages }}", tags: [ 'packages_cui_workstation' ] }
    - { role: install.list.system.packages, packages_list: "{{ gui_xorg_packages }}", tags: [ 'packages_gui_xorg' ] }
    - { role: install.list.system.packages, packages_list: "{{ gui_awesome_wm_packages }}", tags: [ 'packages_gui_awesome_wm' ] }
    - { role: install.list.system.packages, packages_list: "{{ gui_font_packages }}", tags: [ 'packages_gui_fonts' ] }
    - { role: install.list.system.packages, packages_list: "{{ gui_apps_packages }}", tags: [ 'packages_gui_apps' ] }
# os-sudo.yml
#    - { role: install.bin.yaourt, tags: [ 'yaourt' ] }
#    - { role: install.list.aur.packages, packages_list: "{{ cui_aur_packages }}", tags: [ 'packages_cui_aur' ] }
#    - { role: install.list.aur.packages , packages_list: "{{ gui_aur_packages }}", tags: [ 'packages_gui_aur' ] }

  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'

# suite-latex.yml
# suite-office.yml

# devel-python.yml
# devel-ruby.yml
# devel-js.yml
# devel-java.yml
# devel-r.yml
# devel-haskell.yml

# homeshick-dotfile.yml
# home.yml

# dotfiles-apps.yml
# dotfiles-awesome.yml
# dotfiles-task.yml
# dotfiles-tmux.yml
# dotfiles-vim.yml
# dotfiles.yml
# dotfiles-zsh.yml
#
# lin-dev.yml
#
# os-locale.yml
# os-aur.yml
# os-cron.yml
# os-ntp.yml
# os-sudo.yml
# os-mount-nfs-cache.yml
# os-network-wifi.yml
# os-network-wired.yml
# os-pacman.yml
# os-pkgfile.yml
# os-update-packages-cache.yml
# os-upgrade-distro.yml
# #os-systemd.yml
#
# shared.yml
#
# users.yml
# xorg-virtualbox.yml
# xorg-x230.yml
#
# service-ssh.yml
# service-firewall-base.yml
# service-firewall-ssh.yml
#
# pam-auth-fprintd.yml
