  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  # vars_files:
  #  - vars/{{ config_file }}.yml

---
- hosts: localhost
  connection: local

  #vars_files:
  #  - vars/main.yml

  vars:
    - ansible_python_interpreter: /usr/bin/python2

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    # Base configs
    # OK
    ##- include: tasks/mount-nfs-cache.yml
    ###- include: tasks/upgrade-distro.yml
    ##- include: tasks/update-packages-cache.yml
    ##- include: tasks/pacman.yml
    #- include: tasks/aur.yml
    #- include: tasks/ntp.yml
    #- include: tasks/network-wired.yml
    #- include: tasks/network-wifi.yml
    #- include: tasks/ssh.yml

    # Packages
    # OK
    #- include: tasks/cui.yml
    #- include: tasks/devel-python.yml
    #- include: tasks/devel-ruby.yml user="{{ username }}"
    #- include: tasks/devel-java.yml
    #- include: tasks/devel-js.yml
    #- include: tasks/gui.yml

    # Office
    - include: tasks/office.yml

    # System configs
    # OK
    #- include: tasks/cron.yml
    #- include: tasks/systemd.yml
    #- include: tasks/xorg-virtualbox.yml
    #- include: tasks/shared.yml
    #- include: tasks/pkgfile.yml

#TODO:
# yaourt -S vim-youcompleteme-git
# yaourt -S hopenpgp-tools-git
# yaourt -S vim-gnupg
# Create a dotfiles bootstrap

#REPOS:
# Infinality patch
# BBQlinux
# Repo-CK
# Xyne
