#!/usr/bin/env ansible-playbook --inventory-file=inventory

---
- hosts: all

  roles:
    - { role: setup.os, os_feature: "sudo",                                                     tags: [ 'os_sudo' ] }   # sudo

  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
