  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  # vars_files:
  #  - vars/{{ config_file }}.yml

---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    # Service related
    #- include: tasks/pacman.yml
    #- include: tasks/aur.yml
    #- include: tasks/ntp.yml
    #- include: tasks/network-wired.yml
    #- include: tasks/network-wifi.yml
    #- include: tasks/ssh.yml

    # Packages
    #- include: tasks/cui.yml
    #- include: tasks/devel-python.yml
    #- include: tasks/devel-ruby.yml user=afu
    #- include: tasks/devel-java.yml
    - include: tasks/gui.yml

    # System configs
    #- include: tasks/cron.yml
    #- include: tasks/systemd.yml
    #- include: tasks/xorg-virtualbox.yml
    #- include: tasks/shared.yml
    - include: tasks/pkgfile.yml

    # Dotfiles (root)
    #- include: tasks/zsh.yml user=root
    #- include: tasks/vim.yml user=root
    #- include: tasks/tmux.yml user=root

    # Dotfiles (user)
    #- include: tasks/zsh.yml user=afu
    #- include: tasks/vim.yml user=afu
    #- include: tasks/tmux.yml user=afu
