  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  # vars_files:
  #  - vars/{{ config_file }}.yml

---
- hosts: localhost
  connection: local

  #vars_files:
  #  - vars/main.yml

  vars:
    - ansible_python_interpreter: /usr/bin/python2

  tasks:
    - name: Get size of long to determine architecture
      command: getconf LONG_BIT
      register: long_bit
      changed_when: false

    # Used, hackily, to not reinstall AUR packages
    - name: Get list of installed packages
      command: pacman -Qq
      register: installed_packages
      changed_when: false

    # Base configs
    # OK
    ##- include: tasks/mount-nfs-cache.yml
    ###- include: tasks/upgrade-distro.yml
    ##- include: tasks/update-packages-cache.yml
    ##- include: tasks/pacman.yml
    #- include: tasks/aur.yml
    #- include: tasks/ntp.yml
    #- include: tasks/network-wired.yml
    #- include: tasks/network-wifi.yml
    #- include: tasks/ssh.yml

    # Packages
    # OK
    #- include: tasks/cui.yml
    #- include: tasks/devel-python.yml
    #- include: tasks/devel-ruby.yml user="{{ username }}"
    #- include: tasks/devel-java.yml
    #- include: tasks/gui.yml

    # System configs
    # OK
    #- include: tasks/cron.yml
    #- include: tasks/systemd.yml
    #- include: tasks/xorg-virtualbox.yml
    #- include: tasks/shared.yml
    #- include: tasks/pkgfile.yml

    # Dotfiles (root)
    # OK
    #- include: tasks/user.yml user=root
    #- include: tasks/home.yml user=root
    #- include: tasks/zsh.yml user=root
    #- include: tasks/vim.yml user=root
    #- include: tasks/tmux.yml user=root

    # Dotfiles (user)
    # OK
    #- include: tasks/user.yml user=av
    #- include: tasks/home.yml user="{{ username }}"
    - include: tasks/dotfiles-apps.yml  user="{{ username }}" base_config_repo_url="https://github.com/vonpupp" config_repo=apps.dotfiles
    #- include: tasks/zsh.yml  user="{{ username }}" base_config_repo_url="https://github.com/vonpupp" config_repo=zsh.castle
    #- include: tasks/tmux.yml user="{{ username }}" base_config_repo_url="https://github.com/vonpupp" config_repo=tmux.castle
    #- include: tasks/vim.yml  user="{{ username }}" base_config_repo_url="https://github.com/vonpupp" config_repo=vim.castle

#TODO:
# yaourt -S vim-youcompleteme-git
# yaourt -S hopenpgp-tools-git
# yaourt -S vim-gnupg
# Create a dotfiles bootstrap

#REPOS:
# Infinality patch
# BBQlinux
# Repo-CK
# Xyne
