---
- name: Create local user for makepkg
  sudo: yes
  user: name=makepkg shell=/bin/sh

- name: Copy aur script
  sudo: yes
  copy: src=files/bin/aur dest=/usr/local/bin/aur mode=755

- name: Install base-devel dependency
  sudo: yes
  pacman: name=base-devel state=present

- name: Install package-query dependency (yajl)
  sudo: yes
  pacman: name=yajl state=present

- name: Install yaourt dependency (package-query)
  sudo: yes
  command: aur package-query
  when: "'package-query' not in installed_packages.stdout_lines"

- name: Install yaourt
  sudo: yes
  command: aur yaourt
  when: "'yaourt' not in installed_packages.stdout_lines"
