# Missing:
# fortune
# gcalcli
# kpcli
# lm-sensors
# spell-pt
# alsamixer

- name: Install utilities
  sudo: yes
  package: name={{ item }} state=latest
  with_items:
    - abook
    - ack
    - acpi
    - alsa-plugins
    - alsa-utils
    - android-tools
    - android-udev
    - aria2
    - aspell
    - aspell-en
    - aspell-es
    - aspell-fr
    - aspell-it
    - at
    - atop
    - atool
    - autoconf
    - autofs
    - autofs
    - bc
    - bitlbee
    - bower
    - chromaprint
    - cmake
    - cmus
    - curl
    - colordiff
    - cpio
    - ctags
    - cups
    - curl
    - dnsutils
    - docker
    - dosfstools
    - elinks
    - fortune-mod
    - git
    - gnupg
    - gparted
    - haveged
    - highlight
    - hostapd
    - hplip
    - htop
    - iftop
    - imagemagick
    - iptraf-ng
    - irssi
    - ispell
    - isync
    - lftp
    - lm_sensors
    - lsof
    - libvirt
    - lxc
    - lynx
    - mc
    - moreutils
    - mpc
    - mpd
    - mpv
      #- mutt
    - ncmpcpp
    - net-tools
    - networkmanager
    - newsbeuter
    - nfs-utils
    - nmap
    - nodejs
    - notmuch
    - notmuch-mutt
    - ntfsprogs
    - ntp
    - offlineimap
    - p7zip
    - parted
    - perl-datetime
    - perl-image-exiftool
    - pinentry
    - pm-utils
    - polipo
    - procmail
    - pulseaudio
    - pwgen
    - pydf
    - python2
    - python2-pip
      #- qemu
    - ranger
      #- reflector
    - rsync
    - rtorrent
    - rxvt-unicode-terminfo
    - screen
    - scrot
    - smplayer
    - sshfs
    - sudo
    - tar
    - task
    - tmux
    - tree
    - udevil
    - ufw
    - ufw-extras
    - unrar
    - unzip
      #- vagrant
    - vim
      #- virtualbox
      #- virtualbox-ext-vnc
      #- virtualbox-guest-iso
    - w3m
    - wget
    - whois
    #- wicd
    - zip
    - zsh
    - zsh-syntax-highlighting
  #loop_control:
    #msg: "package item={{item.name}}"

# Failing packages: lynx, mpv, offlineimap, smplayer
# To test: finch, cmus, cmatrix, sc, teapot, calcurse, cal, cone, cortex
- name: Start and enable services
  sudo: yes
  service: name={{ item }} state=started enabled=yes
  with_items:
    - NetworkManager
    - atd
    - docker
    - libvirtd
    - remote-fs.target
    - nfs-client.target
    - rpcbind.service
    - autofs.service
    #- wicd

- name: Install yaourt packages
  yaourt: name={{ item }}
  with_items:
    - archey3
    - autoenv-git
    - docker-compose
    - docker-machine
      ##- kitematic
      ##- dropbox
      ##- dropbox-cli
      #- kpcli
    - neomutt
      #- mutt-sidebar-hg
      #- rainbowstream
      ##- sublime-text # sublime-text-dev
      ##- telegram-git
      ##- telegram-purple-git
      #- urlview
      ##- virtualbox-ext-oracle

## Copy the dropbox file first
#- name: Start and enable other services
#  sudo: yes
#  service: name={{ item }} state=started enabled=yes
#  with_items:
#    - dropbox@av
