- name: Install java devel env
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - android-tools
    - android-udev

- name: Install java runtime environment
  sudo: yes
  yaourt: name={{ item }} state=present
  with_items:
    - jre
