---
- name: Install xorg
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - mesa
    - redshift
    - xorg-server
    - xorg-server-utils
    - xorg-server-xephyr
    - xorg-xev
    - xorg-xauth
    - xorg-xinit
    - xorg-xkill
    - xorg-xmodmap
    - xorg-xprop
    - xorg-xrandr
    - xorg-xrdb
    - xorg-xset
    - xorg-xhost

- name: Install windows manager
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    #- slock
    - archlinux-xdg-menu
    - awesome
    - nm-connection-editor
    - networkmanager-qt
    - i3lock
    - slim
    - udisks
    - vicious
    - wmname
    - xautolock
    - xclip
    - xscreensaver
    - xterm

- name: Enable slim
  sudo: yes
  service: name=slim state=started enabled=yes

- name: Set up terminal fonts
  sudo: yes
  pacman: name={{ item }}
  with_items:
    - terminus-font
    - ttf-inconsolata
    - ttf-droid

- name: Install X apps
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    #- seahorse
    - alsa-utils
    - dmenu
    - evince            # gmote-server dependency
    - feh
    - file-roller
    - firefox
    - flashplayer
    - gedit
    - ghostscript
    - gparted
    - gqview
    - gvfs
    - imagemagick
    - libnotify
    - lilyterm
    - meld
    - pcmanfm
    - pidgin
    - qmmp
    - qt4
    - rxvt-unicode
    - shotwell
    - shutter
    - tk
    - vlc
    #- wicd-gtk
    # Add multilib repo
    - wmctrl
    - xfce4-notifyd
    - zathura
    - zathura-pdf-poppler
    #- zathura-pdf-mupdf

- name: Copy .xinitrc
  copy: src=files/.xinitrc dest=~{{ username }}/.xinitrc

- name: Install yaourt packages
#  sudo: yes
#  sudo_user: makepkg
  yaourt: name={{ item }}
  with_items:
    - android-file-transfer
    - autokey-py3
    - gmote-server
    - google-chrome
    - google-talkplugin
    - ice-ssb
    - inox
    - kbdd
    - keepassx-git
    - mkvtoolnix
    - obs-studio-git
    - purple-whatsapp-git
    - qdirstat
    - quvi
    - synapse
    - telegram-purple-git
    - unagi
    - urxvt-perls
    - virt-manager
    - vivaldi
    - wine
    - xarchiver
    - xiphos
    - zeal

- name: Install drivers
  yaourt: name=nvidia

# intel graphics
# $ pacman -S xf86-video-intel libva-intel-driver
#
# # laptop touchpad
# $ pacman -S xf86-input-synaptics
