---
- name: Install xorg
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - xorg-server
    - xorg-server-utils
    - xorg-server-xephyr
    - xorg-xmodmap
    - xorg-xrandr
    - xorg-xinit
    - xorg-xset
    - xorg-xrdb
    - mesa

- name: Install windows manager
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - slim
    - slock
    - awesome
    - vicious
    - xscreensaver
    - wmname
    - xterm
    - xclip

- name: Enable slim
  sudo: yes
  service: name=slim state=started enabled=yes

- name: Set up terminal fonts
  sudo: yes
  pacman: name={{ item }}
  with_items:
    - terminus-font
    - ttf-inconsolata
    - ttf-droid

- name: Install X tools
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - feh
    - firefox
    - gparted
    - keepassx
    - lilyterm
    - mkvtoolnix
    - pcmanfm
    - qmmp
    - qt4
    - seahorse
    - shotwell
    - vlc
    - wicd-gtk
    - wmctrl
    - zathura
    - zathura-pdf-poppler
    - imagemagick
    - ghostscript
    - rxvt-unicode
    - alsa-utils
    - libnotify
    - xfce4-notifyd
    - virt-manager
    - dmenu
    #- zathura-pdf-mupdf

- name: Copy .xinitrc
  copy: src=files/.xinitrc dest=~{{ username }}/.xinitrc

- name: Install urxvt Perl extensions
  yaourt: name=urxvt-perls
#  sudo: yes
#  sudo_user: makepkg

- name: Install Google Chrome
  yaourt: name=google-chrome
#  sudo: yes
#  sudo_user: makepkg

- name: Install Hangouts video plugin
  yaourt: name=google-talkplugin
#  sudo: yes
#  sudo_user: makepkg

# intel graphics
# $ pacman -S xf86-video-intel libva-intel-driver
#
# # laptop touchpad
# $ pacman -S xf86-input-synaptics
