---
- name: Install xorg
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    - mesa
    - redshift
    - xorg-server
    - xorg-server-utils
    - xorg-server-xephyr
    - xorg-xev
    - xorg-xinit
    - xorg-xkill
    - xorg-xmodmap
    - xorg-xrandr
    - xorg-xrdb
    - xorg-xset

- name: Install windows manager
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    #- slock
    - archlinux-xdg-menu
    - awesome
    - i3lock
    - slim
    - udisks
    - vicious
    - wmname
    - xautolock
    - xclip
    - xscreensaver
    - xterm

- name: Enable slim
  sudo: yes
  service: name=slim state=started enabled=yes

- name: Set up terminal fonts
  sudo: yes
  pacman: name={{ item }}
  with_items:
    - terminus-font
    - ttf-inconsolata
    - ttf-droid

- name: Install X tools
  sudo: yes
  pacman: name={{ item }} state=present
  with_items:
    #- seahorse
    - alsa-utils
    - dmenu
    - feh
    - firefox
    - gedit
    - ghostscript
    - gparted
    - imagemagick
    - libnotify
    - lilyterm
    - mkvtoolnix
    - pcmanfm
    - qmmp
    - qt4
    - rxvt-unicode
    - shotwell
    - virt-manager
    - vlc
    #- wicd-gtk
    - wine
    # Add multilib repo
    - wmctrl
    - xarchiver
    - xfce4-notifyd
    - zathura
    - zathura-pdf-poppler
    #- zathura-pdf-mupdf

- name: Copy .xinitrc
  copy: src=files/.xinitrc dest=~{{ username }}/.xinitrc

- name: Install urxvt Perl extensions
#  sudo: yes
#  sudo_user: makepkg
  yaourt: name={{ item }}
  with_items:
    - urxvt-perls
    - kbdd
    - keepassx-git
    - unagi

- name: Install Google Chrome
  yaourt: name=google-chrome

- name: Install Hangouts video plugin
  yaourt: name=google-talkplugin

# intel graphics
# $ pacman -S xf86-video-intel libva-intel-driver
#
# # laptop touchpad
# $ pacman -S xf86-input-synaptics
