---
- name: Create bin folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/bin"

- name: Create tmp folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/tmp"

- name: Create homesick repos folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/.homesick/repos"

- name: Clone homeshick for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/andsens/homeshick.git dest=~{{ user }}/.homesick/repos/homeshick

  # FASD
- name: Clone fasd for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/clvv/fasd.git dest=~{{ user }}/tmp/fasd

- name: Install fasd for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    cd ~{{ user }}/tmp/fasd
    PREFIX=~{{ user }} make install
    cd ..
    rm -rf ~{{ user }}/tmp/fasd

  # FZF
- name: Clone fzf for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/junegunn/fzf.git dest=~{{ user }}/.fzf

- name: Install fzf for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    ~{{ user }}/.fzf/install

  # BASE16
- name: Clone base16-shell for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/chriskempson/base16-shell.git dest=~{{ user }}/.config/base16-shell

  # CREATE_AP
- name: Clone create_ap for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/oblique/create_ap.git dest=~{{ user }}/bin/create_ap

  # GITFLOW
- name: Download gitflow for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - wget -c https://raw.github.com/nvie/gitflow/develop/contrib/gitflow-installer.sh -P ~{{ user }}/tmp
    - chmod +x ~{{ user }}/tmp/gitflow-installer.sh

- name: Install gitflow for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    INSTALL_PREFIX=~{{ user }}/bin ~{{ user }}/tmp/gitflow-installer.sh
    rm ~{{ user }}/tmp/gitflow-installer.sh
