- name: Configuring locales
  become: yes
  become_method: sudo
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - es_ES.UTF-8
    - pt_BR.UTF-8
    - fr_FR.UTF-8


- name: Set default locale
  lineinfile: dest=/etc/environment state=present regexp="^LC_ALL=" line="LC_ALL=en_US.utf8"
