---
- name: Create vboxmnt group
  sudo: yes
  group: name=vboxmnt state=present

- name: Add local users to vboxmnt group
  sudo: yes
  user: name={{ item }} groups=vboxmnt append=yes
  with_items: users

- name: Get GID for vboxmnt
  shell: 'getent group vboxmnt | cut -d: -f3'
  register: gid
  changed_when: false

- name: Set up shared directory entry in fstab
  sudo: yes
  mount: name=/mnt/shared src=Shared fstype=vboxsf opts="gid={{ gid.stdout }},dmode=770,fmode=660" state=present

- name: Create /mnt/shared
  sudo: yes
  file: dest=/mnt/shared state=directory
