---
- name: Install tmux for {{ user }}
  sudo: yes
  pacman: name=tmux state=present

  # TMUX
- name: Link castle for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    git clone https://github.com/vonpupp/{{ item }} ~{{ user }}/.homesick/repos/{{ item }} && source ~{{ user }}/.homesick/repos/homeshick/homeshick.sh && homeshick link {{ item }}
  with_items:
    - tmux.castle

- name: Clone tpm for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/tmux-plugins/tpm dest=~{{ user }}/.tmux/plugins/tpm

- name: Activate tpm for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - tmux start-server
    - tmux new-session -d
    - ~{{ user }}/.tmux/plugins/tpm/scripts/install_plugins.sh
    - tmux kill-server
