---
- name: Install tmux for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  pacman: name=tmux state=present

- name: Create homesick repos folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/.homesick/repos"
#  shell: mkdir -p ~/.homesick/repos
#  git: repo=git://github.com/cdown/dotfiles.git dest=~{{ user }}/git/dotfiles accept_hostkey=yes
#  command: ./setup chdir="~{{ user }}/git/dotfiles"

- name: Clone homeshick for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/andsens/homeshick.git dest=~{{ user }}/.homesick/repos/homeshick

  # TMUX
- name: Link castle for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    git clone https://github.com/vonpupp/{{ item }} ~{{ user }}/.homesick/repos/{{ item }} && source ~{{ user }}/.homesick/repos/homeshick/homeshick.sh && homeshick link {{ item }}
  with_items:
    - tmux.castle

- name: Clone tpm for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/tmux-plugins/tpm dest=~{{ user }}/.tmux/plugins/tpm

- name: Activate tpm for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - tmux start-server
    - tmux new-session -d
    - ~{{ user }}/.tmux/plugins/tpm/scripts/install_plugins.sh
    - tmux kill-server
