---
- name: Install vim for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  pacman: name=vim state=present

- name: Create homesick repos folder for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/.homesick/repos"

- name: Clone homeshick for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/andsens/homeshick.git dest=~{{ user }}/.homesick/repos/homeshick

  # VIM
- name: Clone vundle for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/gmariK/vundle.git dest={{ user }}/.vim/bundle/vundle

- name: Configure vim for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    #- mkdir -p ~/.vim/bundle
    - mkdir -p {{ user }}/.vim/colors
    - mkdir -p {{ user }}/.vim/config
    - mkdir -p {{ user }}/.vim/spell
    - mkdir -p {{ user }}/.vim/syntax

  # VIM Castle
- name: Link castle
  shell:
    git clone https://github.com/vonpupp/{{ item }} ~/.homesick/repos/{{ item }} && source {{ user }}/.homesick/repos/homeshick/homeshick.sh && homeshick link {{ item }}
  with_items:
    - vim.castle

#- name: Clone youcompleteme
#  shell:
#    git clone --depth 1 https://github.com/Valloric/YouCompleteMe.git ~/.vim/bundle/YouCompleteMe && cd ~/.vim/bundle/YouCompleteMe && git submodule init && git submodule update --depth 1

- name: Bundle vim for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  command: "{{ item }}"
  with_items:
    - vim +BundleInstall +qall


#- name: Clone dotfiles for {{ user }}
#  sudo: yes
#  sudo_user: "{{ user }}"
#  git: repo=git://github.com/cdown/dotfiles.git dest=~{{ user }}/git/dotfiles accept_hostkey=yes
#
#- name: Set up dotfiles for {{ user }}
#  sudo: yes
#  sudo_user: "{{ user }}"
#  command: ./setup chdir="~{{ user }}/git/dotfiles"
#  changed_when: false
#
#- name: "Set {{ user }}'s dotfiles to push using ssh"
#  sudo: yes
#  sudo_user: "{{ user }}"
#  command: git remote set-url --push origin git@github.com:cdown/dotfiles.git chdir=~{{ user }}/git/dotfiles
#  changed_when: false
