---
- name: Install zsh for {{ user }}
  sudo: yes
  pacman: name=zsh state=present

- name: Set zsh shell for {{ user }}
  sudo: yes
  user: name={{ user }} shell=/bin/zsh

  # ZSH
- name: Clone oh-my-zsh repo for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~{{ user }}/.oh-my-zsh

- name: Link castle for {{ user }}
  sudo: yes
  sudo_user: "{{ user }}"
  shell:
    git clone https://github.com/vonpupp/{{ item }} ~{{ user }}/.homesick/repos/{{ item }} && source ~{{ user }}/.homesick/repos/homeshick/homeshick.sh && homeshick link {{ item }}
  with_items:
    - zsh.castle
