- name: Install java devel env
  become: yes
  become_user: makepkg
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - android-tools
    - android-udev

- name: Install java runtime environment
  become: yes
  become_user: makepkg
  yaourt: name={{ item }} state=present
  with_items:
    - jre
