---
- name: Install python devel env
  become: yes
  pacman: name={{ item }} state=present
  with_items:
    - base-devel
    - tls
#    - python-docs
#    - python-virtualenv
#    - python2
#    - python2-docs
#    - python2-pip
#    - python2-virtualenv

- name: Install pyenv
  yaourt: name=pyenv
  become: yes
  become_user: makepkg

#- name: Get list of Pythons installed in pyenv
#  command: pyenv versions
#  register: pyenv_versions
#  become: yes
#  become_user: "{{ user }}"
#  changed_when: false

- name: Install Pythons using pyenv
  command: "pyenv install {{ item }}"
  with_items:
    - 2.7.12
    - 3.5.2
  become: yes
  become_user: "{{ user }}"
#  when: '"{{ item }}" not in pyenv_versions.stdout'

- name: Get list of Python 3 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell 3.5.2 && pip freeze | awk -F= '{ print $1 }'"
  register: py3_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Get list of Python 2 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell 2.7.12 && pip freeze | awk -F= '{ print $1 }'"
  register: py2_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Python 3 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 3.5.2 && pip install {{ item }}'
  with_items:
    - yturl
    - tzupdate
    - virtualenv
    - virtualenvwrapper
    - astroid
    - pylint
    - twine
    - ipython
    - flake8
    - line-profiler
    - memory-profiler
    - psutil
    - awscli
    - tox
    - pipdeptree
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item | basename }}" not in py3_utils.stdout_lines'

- name: Install Python 2 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell 2.7.12 && pip install {{ item }}'
  with_items:
    - gsutil
    - s3cmd
    - pipdeptree
    - stapler
  become: yes
  become_user: "{{ user }}"
  when: '"{{ item | basename }}" not in py2_utils.stdout_lines'

#- name: Install python pip env
#  become: yes
#  pip: name={{ item }} executable=pip2
#  with_items:
#    - envdir
#    - autoenv
#    - virtualenvwrapper
