#- name: Create sudo group
#  action: group name=sudo state=present system=yes

- include: os-root-sudoers.yml

- name: Create makepkg user
  action: user name=makepkg state=present system=yes

- name: Add makepkg user to the sudoers
  action: 'lineinfile dest=/etc/sudoers.d/makepkg state=present create=yes regexp="makepkg .*" line="makepkg ALL=NOPASSWD: /usr/bin/pacman *"'

- name: Ensure /etc/sudoers.d/makepkg file has correct permissions
  action: file path=/etc/sudoers.d/makepkg mode=0440 state=file owner=root group=root

#- name: Create av user
#  action: user name=av state=present group=sudo system=no
