- name: Install packages
  become: yes
  package:
    name: "{{ service_openssh_package }}"
    state: present

- debug: msg="Trigger ssh handler"
  become: yes
  notify:
    restart ssh
  when:
    not is_travis
