# Guides:
# General X230 configs
# https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X230

# Battery optimization:
# https://wiki.archlinux.org/index.php/TLP
#
# Boost battery to 8/9h per charge
#
# Install:
# tlp
# acpi_call
# lsb-release
# tp_smapi
# x86_energy_perf_policy
#
# Enable:
# tlp.service
# tlp-sleep.service
#
# Mask:
# systemd-rfkill.service
# systemd-rfkill.socket
#

# mkinitcpio
- name: Copy /etc/mkinitcpio.conf
  become: yes
  copy:
    src: files/x230/etc/mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
    owner: root
    group: root
    mode: 0644

# synaptics
- name: Copy /etc/X11/xorg.conf.d/50-synaptics.conf
  become: yes
  copy:
    src: files/x230/etc/X11/xorg.conf.d/50-synaptics.conf
    dest: /etc/X11/xorg.conf.d/50-synaptics.conf
    owner: root
    group: root
    mode: 0644

# tlp
- name: Copy /etc/default/tlp
  become: yes
  copy:
    src: files/x230/etc/default/tlp
    dest: /etc/default/tlp
    owner: root
    group: root
    mode: 0644

# Think pad fan
# https://wiki.archlinux.org/index.php/Fan_speed_control#ThinkPad_laptops
#
- name: Copy /etc/modprobe.d/thinkfan.conf
  become: yes
  copy:
    src: files/x230/etc/modprobe.d/thinkfan_acpi.conf
    dest: /etc/modprobe.d/thinkfan_acpi.conf
    owner: root
    group: root
    mode: 0644

# TODO: modprobe thinkpad_acpi

- name: Copy /etc/default/thinkfan
  become: yes
  copy:
    src: files/x230/etc/default/thinkfan
    dest: /etc/default/thinkfan
    owner: root
    group: root
    mode: 0644

- name: Copy /etc/thinkfan.conf
  become: yes
  copy:
    src: files/x230/etc/thinkfan.conf
    dest: /etc/thinkfan.conf
    owner: root
    group: root
    mode: 0644

# TODO: Fix /etc/thinfan.conf
#- name: Enable thinkfan service
#  become: yes
#  systemd:
#    name: thinkfan
#    enabled: yes
#    state: restarted


# fprintd

- name: Copy /etc/pam.d/system-local-login
  become: yes
  copy:
    src: files/x230/etc/pam.d/system-local-login
    dest: /etc/pam.d/system-local-login
    owner: root
    group: root
    mode: 0644

- name: Enable fprintd service
  become: yes
  systemd:
    name: fprintd
    enabled: yes
    state: restarted

# TODO: MANUALLY ADD A FINGERPRINT WITH: fprintd-enroll

# audio powersave
- name: Copy /etc/modprobe.d/audio_powersave.conf
  become: yes
  copy:
    src: files/x230/etc/modprobe.d/audio_powersave.conf
    dest: /etc/modprobe.d/audio_powersave.conf
    owner: root
    group: root
    mode: 0644

# sysctl watchdog
- name: Copy /etc/sysctl.d/disable_watchdog.conf
  become: yes
  copy:
    src: files/x230/etc/sysctl.d/disable_watchdog.conf
    dest: /etc/sysctl.d/disable_watchdog.conf
    owner: root
    group: root
    mode: 0644

# sysctl laptop
- name: Copy /etc/sysctl.d/laptop.conf
  become: yes
  copy:
    src: files/x230/etc/sysctl.d/laptop.conf
    dest: /etc/sysctl.d/laptop.conf
    owner: root
    group: root
    mode: 0644
