- name: Install packages
  become: yes
  package:
    name: "{{ service_docker_package }}"
    state: present

- debug: msg="Trigger docker handler"
  become: yes
  notify:
    restart docker
  when:
    not is_travis

- name: Restart and enable docker
  become: yes
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: docker
  when:
    not is_travis
