- name: Install packages
  become: yes
  package:
    name: "{{ service_kvm_package }}"
    state: present

- debug: msg="Trigger libvirtd handler"
  become: yes
  notify:
    restart kvm
  changed_when: true

- name: Restart and enable libvirtd
  become: yes
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: libvirtd
  when:
    not is_travis
