---
- include_vars: secrets.yml

- name: Secret3
  become: yes
  become_user: "{{ user }}"
  command: "{{ secret3 }}"

- name: Secret4
  become: yes
  become_user: "{{ user }}"
  command: "{{ secret4 }}"
