- name: Install packages
  become: yes
  package:
    name: "{{ service_ntp_package }}"
    state: present

- debug: msg="Trigger ntpd handler"
  become: yes
  notify:
    restart ntpd
  when:
    not is_travis
