- name: Install packages
  become: yes
  package:
    name: "{{ service_networkmanager_package }}"
    state: present

- debug: msg="Trigger networkmanager handler"
  become: yes
  notify:
    restart networkmanager
  when:
    not is_travis

- name: Restart and enable networkmanager
  become: yes
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: networkmanager
  when:
    not is_travis
