- name: Set git dotfiles base repo URL
  set_fact:
    base_dotfiles_repo_url: "https://vonpupp@github.com/vonpupp"


# Clone and link dotfiles using homeshick
- include: "dotfiles-clone-link.yml"

- name: Install awesome for {{ user }}
  become: yes
  package: name=awesome state=present
