- name: Set git dotfiles base repo URL
  set_fact:
    base_dotfiles_repo_url: "https://vonpupp@github.com/vonpupp"


# Clone and link dotfiles using homeshick
- include: "dotfiles-clone-link.yml"


# Ensure packages
- name: Ensure '{{ loop_var }}' packages
  include_role:
	name: install.list.system.packages
  with_items:
	- "{{ gui_xorg_packages }}"
	- "{{ gui_awesome_wm_packages }}"
  loop_control:
	loop_var: packages_list

#- name: Enable slim
