- name: Create folders
  become: yes
  become_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/{{ item }}"
  with_items:
    - bin
    - tmp
    - .venv
    - .homesick/repos
    - Music
    - Pictures

#- name: Install requirements2.txt for {{ user }}
#  become: yes
#  become_user: "{{ user }}"
#  pip: requirements=~{{ user }}/{{ lookup('pipe','pwd')|dirname|basename }}/files/requirements2.txt virtualenv=~{{ user }}/.venv/bin2 virtualenv_command=virtualenv2 executable=pip2
#
#- name: Install requirements3.txt for {{ user }}
#  become: yes
#  become_user: "{{ user }}"
#  pip: requirements=~{{ user }}/{{ lookup('pipe','pwd')|dirname|basename }}/files/requirements3.txt virtualenv=~{{ user }}/.venv/bin3 virtualenv_command=virtualenv3 executable=pip3

#  # .xinitrc
#- name: Copy .xinitrc
#  become: yes
#  become_user: "{{ user }}"
#  copy: src=files/.xinitrc dest=~{{ user }}/.xinitrc

      #- name: Clone homeshick
      #  become: yes
      #  become_user: "{{ user }}"
      #  git: repo=https://github.com/andsens/homeshick.git dest=~{{ user }}/.homesick/repos/homeshick


# FASD

- name: Clone fasd
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/clvv/fasd.git dest=/tmp/fasd

#- name: Install fasd
#  become: yes
#  become_user: "{{ user }}"
#  command: "{{ item }}"
#  with_items:
#    - cd ~{{ user }}/tmp/fasd
#    - PREFIX=~{{ user }} make install
#    - cd ..
#    - rm -rf ~{{ user }}/tmp/fasd
#    - rm -rf ~{{ user }}/.zshrc

- name: Install fasd
  become: yes
  become_user: "{{ user }}"
  make:
    chdir: /tmp/fasd
    target: install
    params:
      PREFIX: ~{{ user }}

  # FZF
- name: Clone fzf
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/junegunn/fzf.git dest=~{{ user }}/.fzf

- name: Install fzf for {{ user }}
  become: yes
  become_user: "{{ user }}"
  shell:
    ~{{ user }}/.fzf/install --no-update-rc

  # BASE16
- name: Clone base16-shell for {{ user }}
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/chriskempson/base16-shell.git dest=~{{ user }}/.config/base16-shell

  # CREATE_AP
- name: Clone create_ap for {{ user }}
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/oblique/create_ap.git dest=~{{ user }}/bin/create_ap

  # GITFLOW
- name: Download gitflow for {{ user }}
  get_url:
    url: https://raw.github.com/nvie/gitflow/develop/contrib/gitflow-installer.sh
    dest: ~{{ user }}/tmp
    mode: 0755

#- name: Download gitflow for {{ user }}
#  become: yes
#  become_user: "{{ user }}"
#  command: "{{ item }}"
#  with_items:
#    - wget -c https://raw.github.com/nvie/gitflow/develop/contrib/gitflow-installer.sh -P ~{{ user }}/tmp
#    - chmod +x ~{{ user }}/tmp/gitflow-installer.sh

- name: Install gitflow for {{ user }}
  become: yes
  become_user: "{{ user }}"
  shell:
    INSTALL_PREFIX=~{{ user }}/bin ~{{ user }}/tmp/gitflow-installer.sh
    rm ~{{ user }}/tmp/gitflow-installer.sh

- name: Clone autoenv
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/kennethreitz/autoenv dest=~{{ user }}/.autoenv

#- name: Install yaourt tools
#  yaourt: name={{ item }}
#  with_items:
#    - fasd

# TODO:
# - Install: trash, envdir
