---
# Load a variable file based on the OS type, or a default if not found.
#- include_vars: "{{ item }}"
#  with_first_found:
#    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
#    - "../vars/{{ ansible_distribution }}.yml"
#    - "../vars/{{ ansible_os_family }}.yml"
#    - "../vars/default.yml"
#  when: cui_minimal_packages is not defined or cui_virt_packages is not defined or cui_workstation_packages is not defined

- name: Install packages
  become: yes
  include: packages.yml
