  # FOLDERS

- name: Create folders
  become: yes
  become_user: "{{ user }}"
  command: mkdir -p "~{{ user }}/{{ item }}"
  with_items:
    - bin
    - tmp
    - .venv
    - .homesick/repos
    - Music
    - Pictures
